from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from recipes.models import Recipe, Ingredient
from django.utils.text import slugify


class Command(BaseCommand):
    help = "Load sample recipes into the database"

    def handle(self, *args, **options):
        # Get or create a default user
        user, created = User.objects.get_or_create(
            username="chef_test",
            defaults={"email": "chef@example.com", "is_staff": True},
        )
        if created:
            user.set_password("testpassword")
            user.save()

        # Sample recipes data
        sample_recipes = [
            {
                "title": "Classic Chocolate Chip Cookies",
                "description": "Soft and chewy chocolate chip cookies that everyone loves.",
                "servings": 24,
                "prep_time": 15,
                "cook_time": 12,
                "difficulty": "easy",
                "meal_type": "dessert",
                "dietary_restrictions": "none",
                "prep_instructions": "Preheat oven to 375°F. Mix dry ingredients in a bowl.",
                "cook_instructions": "Bake for 10-12 minutes until golden brown. Cool on wire rack.",
                "ingredients": [
                    {"name": "all-purpose flour", "quantity": 2.25, "unit": "cup"},
                    {
                        "name": "butter",
                        "quantity": 1,
                        "unit": "cup",
                        "notes": "softened",
                    },
                    {"name": "brown sugar", "quantity": 0.75, "unit": "cup"},
                    {"name": "white sugar", "quantity": 0.75, "unit": "cup"},
                    {"name": "eggs", "quantity": 2, "unit": "piece"},
                    {"name": "vanilla extract", "quantity": 2, "unit": "tsp"},
                    {"name": "baking soda", "quantity": 1, "unit": "tsp"},
                    {"name": "salt", "quantity": 1, "unit": "tsp"},
                    {"name": "chocolate chips", "quantity": 2, "unit": "cup"},
                ],
            },
            {
                "title": "Chicken Stir Fry",
                "description": "Quick and healthy chicken stir fry with fresh vegetables.",
                "servings": 4,
                "prep_time": 20,
                "cook_time": 15,
                "difficulty": "medium",
                "meal_type": "dinner",
                "dietary_restrictions": "none",
                "prep_instructions": "Cut chicken into bite-sized pieces. Chop all vegetables.",
                "cook_instructions": "Heat oil in wok. Cook chicken first, then add vegetables. Stir fry until tender.",
                "ingredients": [
                    {
                        "name": "chicken breast",
                        "quantity": 1,
                        "unit": "lb",
                        "notes": "boneless, skinless",
                    },
                    {
                        "name": "bell peppers",
                        "quantity": 2,
                        "unit": "piece",
                        "notes": "mixed colors",
                    },
                    {
                        "name": "broccoli",
                        "quantity": 2,
                        "unit": "cup",
                        "notes": "cut into florets",
                    },
                    {
                        "name": "carrots",
                        "quantity": 2,
                        "unit": "piece",
                        "notes": "julienned",
                    },
                    {
                        "name": "garlic",
                        "quantity": 3,
                        "unit": "clove",
                        "notes": "minced",
                    },
                    {"name": "soy sauce", "quantity": 3, "unit": "tbsp"},
                    {"name": "vegetable oil", "quantity": 2, "unit": "tbsp"},
                    {"name": "sesame oil", "quantity": 1, "unit": "tsp"},
                ],
            },
            {
                "title": "Avocado Toast",
                "description": "Simple and nutritious avocado toast with a twist.",
                "servings": 2,
                "prep_time": 10,
                "cook_time": 5,
                "difficulty": "easy",
                "meal_type": "breakfast",
                "dietary_restrictions": "vegetarian",
                "prep_instructions": "Toast bread. Mash avocado with lime juice and seasonings.",
                "cook_instructions": "Spread avocado on toast. Top with desired toppings.",
                "ingredients": [
                    {"name": "whole grain bread", "quantity": 2, "unit": "piece"},
                    {
                        "name": "avocado",
                        "quantity": 1,
                        "unit": "piece",
                        "notes": "ripe",
                    },
                    {"name": "lime juice", "quantity": 1, "unit": "tbsp"},
                    {"name": "salt", "quantity": 0.25, "unit": "tsp"},
                    {"name": "black pepper", "quantity": 0.125, "unit": "tsp"},
                    {
                        "name": "cherry tomatoes",
                        "quantity": 4,
                        "unit": "piece",
                        "notes": "halved",
                    },
                ],
            },
            {
                "title": "Beef Tacos",
                "description": "Flavorful ground beef tacos with fresh toppings.",
                "servings": 6,
                "prep_time": 15,
                "cook_time": 20,
                "difficulty": "easy",
                "meal_type": "dinner",
                "dietary_restrictions": "none",
                "prep_instructions": "Prepare all toppings. Heat taco shells.",
                "cook_instructions": "Brown ground beef. Add seasonings and simmer. Assemble tacos.",
                "ingredients": [
                    {"name": "ground beef", "quantity": 1, "unit": "lb"},
                    {"name": "taco shells", "quantity": 12, "unit": "piece"},
                    {"name": "onion", "quantity": 1, "unit": "piece", "notes": "diced"},
                    {"name": "taco seasoning", "quantity": 1, "unit": "oz"},
                    {
                        "name": "lettuce",
                        "quantity": 2,
                        "unit": "cup",
                        "notes": "shredded",
                    },
                    {
                        "name": "cheese",
                        "quantity": 1,
                        "unit": "cup",
                        "notes": "shredded cheddar",
                    },
                    {
                        "name": "tomatoes",
                        "quantity": 2,
                        "unit": "piece",
                        "notes": "diced",
                    },
                    {"name": "sour cream", "quantity": 0.5, "unit": "cup"},
                ],
            },
            {
                "title": "Vegan Buddha Bowl",
                "description": "Nutritious bowl with quinoa, roasted vegetables, and tahini dressing.",
                "servings": 4,
                "prep_time": 25,
                "cook_time": 35,
                "difficulty": "medium",
                "meal_type": "lunch",
                "dietary_restrictions": "vegan",
                "prep_instructions": "Cook quinoa. Chop vegetables. Preheat oven to 425°F.",
                "cook_instructions": "Roast vegetables. Prepare dressing. Assemble bowls.",
                "ingredients": [
                    {"name": "quinoa", "quantity": 1, "unit": "cup"},
                    {
                        "name": "sweet potato",
                        "quantity": 2,
                        "unit": "piece",
                        "notes": "cubed",
                    },
                    {
                        "name": "chickpeas",
                        "quantity": 1,
                        "unit": "cup",
                        "notes": "cooked",
                    },
                    {"name": "kale", "quantity": 4, "unit": "cup", "notes": "massaged"},
                    {"name": "tahini", "quantity": 3, "unit": "tbsp"},
                    {"name": "lemon juice", "quantity": 2, "unit": "tbsp"},
                    {"name": "olive oil", "quantity": 2, "unit": "tbsp"},
                    {
                        "name": "garlic",
                        "quantity": 2,
                        "unit": "clove",
                        "notes": "minced",
                    },
                ],
            },
            {
                "title": "Pancakes",
                "description": "Fluffy homemade pancakes perfect for weekend mornings.",
                "servings": 4,
                "prep_time": 10,
                "cook_time": 15,
                "difficulty": "easy",
                "meal_type": "breakfast",
                "dietary_restrictions": "vegetarian",
                "prep_instructions": "Mix dry ingredients. In another bowl, whisk wet ingredients.",
                "cook_instructions": "Combine wet and dry ingredients. Cook on griddle until bubbles form.",
                "ingredients": [
                    {"name": "all-purpose flour", "quantity": 1.5, "unit": "cup"},
                    {"name": "sugar", "quantity": 3, "unit": "tbsp"},
                    {"name": "baking powder", "quantity": 2, "unit": "tsp"},
                    {"name": "salt", "quantity": 0.5, "unit": "tsp"},
                    {"name": "milk", "quantity": 1.25, "unit": "cup"},
                    {"name": "egg", "quantity": 1, "unit": "piece"},
                    {
                        "name": "butter",
                        "quantity": 3,
                        "unit": "tbsp",
                        "notes": "melted",
                    },
                ],
            },
            {
                "title": "Caesar Salad",
                "description": "Classic Caesar salad with homemade dressing and croutons.",
                "servings": 4,
                "prep_time": 20,
                "cook_time": 10,
                "difficulty": "medium",
                "meal_type": "lunch",
                "dietary_restrictions": "vegetarian",
                "prep_instructions": "Wash and chop lettuce. Make croutons and dressing.",
                "cook_instructions": "Toast croutons. Toss salad with dressing.",
                "ingredients": [
                    {
                        "name": "romaine lettuce",
                        "quantity": 1,
                        "unit": "piece",
                        "notes": "chopped",
                    },
                    {
                        "name": "parmesan cheese",
                        "quantity": 0.5,
                        "unit": "cup",
                        "notes": "grated",
                    },
                    {
                        "name": "bread",
                        "quantity": 2,
                        "unit": "cup",
                        "notes": "cubed for croutons",
                    },
                    {"name": "mayonnaise", "quantity": 0.5, "unit": "cup"},
                    {"name": "lemon juice", "quantity": 2, "unit": "tbsp"},
                    {
                        "name": "garlic",
                        "quantity": 2,
                        "unit": "clove",
                        "notes": "minced",
                    },
                    {"name": "anchovy paste", "quantity": 1, "unit": "tsp"},
                ],
            },
            {
                "title": "Spaghetti Carbonara",
                "description": "Classic Italian pasta dish with eggs, cheese, and pancetta.",
                "servings": 4,
                "prep_time": 15,
                "cook_time": 20,
                "difficulty": "medium",
                "meal_type": "dinner",
                "dietary_restrictions": "none",
                "prep_instructions": "Cook pasta. Whisk eggs with cheese. Prepare pancetta.",
                "cook_instructions": "Cook pancetta until crispy. Toss hot pasta with egg mixture.",
                "ingredients": [
                    {"name": "spaghetti", "quantity": 1, "unit": "lb"},
                    {"name": "pancetta", "quantity": 6, "unit": "oz", "notes": "diced"},
                    {"name": "eggs", "quantity": 4, "unit": "piece"},
                    {
                        "name": "parmesan cheese",
                        "quantity": 1,
                        "unit": "cup",
                        "notes": "grated",
                    },
                    {
                        "name": "black pepper",
                        "quantity": 1,
                        "unit": "tsp",
                        "notes": "freshly ground",
                    },
                    {"name": "salt", "quantity": 0.5, "unit": "tsp"},
                ],
            },
            {
                "title": "Chocolate Muffins",
                "description": "Rich and moist chocolate muffins perfect for breakfast or snack.",
                "servings": 12,
                "prep_time": 15,
                "cook_time": 18,
                "difficulty": "easy",
                "meal_type": "snack",
                "dietary_restrictions": "vegetarian",
                "prep_instructions": "Preheat oven to 375°F. Mix dry ingredients separately from wet.",
                "cook_instructions": "Combine wet and dry ingredients. Bake until toothpick comes out clean.",
                "ingredients": [
                    {"name": "all-purpose flour", "quantity": 1.75, "unit": "cup"},
                    {"name": "cocoa powder", "quantity": 0.25, "unit": "cup"},
                    {"name": "sugar", "quantity": 0.75, "unit": "cup"},
                    {"name": "baking powder", "quantity": 2, "unit": "tsp"},
                    {"name": "salt", "quantity": 0.5, "unit": "tsp"},
                    {"name": "milk", "quantity": 1, "unit": "cup"},
                    {"name": "vegetable oil", "quantity": 0.33, "unit": "cup"},
                    {"name": "egg", "quantity": 1, "unit": "piece"},
                    {"name": "vanilla extract", "quantity": 1, "unit": "tsp"},
                ],
            },
            {
                "title": "Greek Salad",
                "description": "Fresh Mediterranean salad with feta cheese and olives.",
                "servings": 6,
                "prep_time": 15,
                "cook_time": 0,
                "difficulty": "easy",
                "meal_type": "lunch",
                "dietary_restrictions": "vegetarian",
                "prep_instructions": "Chop all vegetables. Prepare dressing.",
                "cook_instructions": "No cooking required. Toss all ingredients with dressing.",
                "ingredients": [
                    {
                        "name": "cucumber",
                        "quantity": 2,
                        "unit": "piece",
                        "notes": "diced",
                    },
                    {
                        "name": "tomatoes",
                        "quantity": 4,
                        "unit": "piece",
                        "notes": "wedged",
                    },
                    {
                        "name": "red onion",
                        "quantity": 0.5,
                        "unit": "piece",
                        "notes": "sliced",
                    },
                    {
                        "name": "feta cheese",
                        "quantity": 6,
                        "unit": "oz",
                        "notes": "cubed",
                    },
                    {"name": "kalamata olives", "quantity": 0.5, "unit": "cup"},
                    {"name": "olive oil", "quantity": 0.25, "unit": "cup"},
                    {"name": "lemon juice", "quantity": 2, "unit": "tbsp"},
                    {"name": "oregano", "quantity": 1, "unit": "tsp", "notes": "dried"},
                ],
            },
            {
                "title": "Banana Bread",
                "description": "Moist and delicious banana bread made with overripe bananas.",
                "servings": 8,
                "prep_time": 15,
                "cook_time": 60,
                "difficulty": "easy",
                "meal_type": "snack",
                "dietary_restrictions": "vegetarian",
                "prep_instructions": "Preheat oven to 350°F. Mash bananas. Mix wet and dry ingredients separately.",
                "cook_instructions": "Combine ingredients. Bake in loaf pan for 55-65 minutes.",
                "ingredients": [
                    {
                        "name": "bananas",
                        "quantity": 3,
                        "unit": "piece",
                        "notes": "overripe, mashed",
                    },
                    {
                        "name": "butter",
                        "quantity": 0.33,
                        "unit": "cup",
                        "notes": "melted",
                    },
                    {"name": "sugar", "quantity": 0.75, "unit": "cup"},
                    {"name": "egg", "quantity": 1, "unit": "piece", "notes": "beaten"},
                    {"name": "vanilla extract", "quantity": 1, "unit": "tsp"},
                    {"name": "baking soda", "quantity": 1, "unit": "tsp"},
                    {"name": "salt", "quantity": 0.25, "unit": "tsp"},
                    {"name": "all-purpose flour", "quantity": 1.5, "unit": "cup"},
                ],
            },
            {
                "title": "Chicken Soup",
                "description": "Comforting homemade chicken soup with vegetables.",
                "servings": 6,
                "prep_time": 20,
                "cook_time": 45,
                "difficulty": "medium",
                "meal_type": "lunch",
                "dietary_restrictions": "none",
                "prep_instructions": "Chop vegetables. Season chicken.",
                "cook_instructions": "Sauté vegetables. Add chicken and broth. Simmer until chicken is cooked.",
                "ingredients": [
                    {
                        "name": "chicken breast",
                        "quantity": 1,
                        "unit": "lb",
                        "notes": "cubed",
                    },
                    {
                        "name": "carrots",
                        "quantity": 3,
                        "unit": "piece",
                        "notes": "sliced",
                    },
                    {
                        "name": "celery",
                        "quantity": 3,
                        "unit": "piece",
                        "notes": "chopped",
                    },
                    {"name": "onion", "quantity": 1, "unit": "piece", "notes": "diced"},
                    {"name": "chicken broth", "quantity": 6, "unit": "cup"},
                    {"name": "egg noodles", "quantity": 2, "unit": "cup"},
                    {"name": "thyme", "quantity": 1, "unit": "tsp", "notes": "dried"},
                    {"name": "salt", "quantity": 1, "unit": "tsp"},
                    {"name": "black pepper", "quantity": 0.5, "unit": "tsp"},
                ],
            },
            {
                "title": "Veggie Burger",
                "description": "Healthy homemade veggie burger with black beans and vegetables.",
                "servings": 4,
                "prep_time": 30,
                "cook_time": 20,
                "difficulty": "medium",
                "meal_type": "lunch",
                "dietary_restrictions": "vegetarian",
                "prep_instructions": "Mash beans. Sauté vegetables. Mix all ingredients.",
                "cook_instructions": "Form patties. Cook on griddle until crispy outside.",
                "ingredients": [
                    {
                        "name": "black beans",
                        "quantity": 1,
                        "unit": "cup",
                        "notes": "cooked and mashed",
                    },
                    {"name": "breadcrumbs", "quantity": 0.5, "unit": "cup"},
                    {
                        "name": "onion",
                        "quantity": 0.5,
                        "unit": "piece",
                        "notes": "minced",
                    },
                    {
                        "name": "bell pepper",
                        "quantity": 0.5,
                        "unit": "piece",
                        "notes": "minced",
                    },
                    {
                        "name": "garlic",
                        "quantity": 2,
                        "unit": "clove",
                        "notes": "minced",
                    },
                    {"name": "egg", "quantity": 1, "unit": "piece"},
                    {"name": "cumin", "quantity": 1, "unit": "tsp"},
                    {"name": "paprika", "quantity": 0.5, "unit": "tsp"},
                    {"name": "salt", "quantity": 0.5, "unit": "tsp"},
                ],
            },
            {
                "title": "Apple Pie",
                "description": "Classic American apple pie with flaky crust and cinnamon apples.",
                "servings": 8,
                "prep_time": 45,
                "cook_time": 50,
                "difficulty": "hard",
                "meal_type": "dessert",
                "dietary_restrictions": "vegetarian",
                "prep_instructions": "Make pie crust. Peel and slice apples. Mix filling.",
                "cook_instructions": "Assemble pie. Bake until crust is golden and filling is bubbly.",
                "ingredients": [
                    {
                        "name": "apples",
                        "quantity": 6,
                        "unit": "piece",
                        "notes": "Granny Smith, peeled and sliced",
                    },
                    {"name": "sugar", "quantity": 0.75, "unit": "cup"},
                    {"name": "flour", "quantity": 2, "unit": "tbsp"},
                    {"name": "cinnamon", "quantity": 1, "unit": "tsp"},
                    {"name": "nutmeg", "quantity": 0.25, "unit": "tsp"},
                    {
                        "name": "pie crust",
                        "quantity": 2,
                        "unit": "piece",
                        "notes": "homemade or store-bought",
                    },
                    {"name": "butter", "quantity": 2, "unit": "tbsp", "notes": "cubed"},
                    {
                        "name": "egg",
                        "quantity": 1,
                        "unit": "piece",
                        "notes": "for egg wash",
                    },
                ],
            },
            {
                "title": "Shrimp Scampi",
                "description": "Elegant shrimp dish with garlic, white wine, and butter.",
                "servings": 4,
                "prep_time": 15,
                "cook_time": 15,
                "difficulty": "medium",
                "meal_type": "dinner",
                "dietary_restrictions": "none",
                "prep_instructions": "Clean shrimp. Mince garlic. Cook pasta.",
                "cook_instructions": "Sauté garlic. Add shrimp and wine. Toss with pasta.",
                "ingredients": [
                    {
                        "name": "shrimp",
                        "quantity": 1,
                        "unit": "lb",
                        "notes": "peeled and deveined",
                    },
                    {"name": "linguine", "quantity": 12, "unit": "oz"},
                    {
                        "name": "garlic",
                        "quantity": 4,
                        "unit": "clove",
                        "notes": "minced",
                    },
                    {"name": "white wine", "quantity": 0.5, "unit": "cup"},
                    {"name": "butter", "quantity": 4, "unit": "tbsp"},
                    {"name": "olive oil", "quantity": 2, "unit": "tbsp"},
                    {
                        "name": "parsley",
                        "quantity": 0.25,
                        "unit": "cup",
                        "notes": "chopped",
                    },
                    {"name": "red pepper flakes", "quantity": 0.25, "unit": "tsp"},
                    {"name": "lemon juice", "quantity": 2, "unit": "tbsp"},
                ],
            },
            {
                "title": "Smoothie Bowl",
                "description": "Healthy and colorful smoothie bowl with fresh fruits and toppings.",
                "servings": 2,
                "prep_time": 10,
                "cook_time": 0,
                "difficulty": "easy",
                "meal_type": "breakfast",
                "dietary_restrictions": "vegan",
                "prep_instructions": "Freeze fruits overnight. Prepare toppings.",
                "cook_instructions": "Blend frozen fruits until thick. Top with fresh fruits and nuts.",
                "ingredients": [
                    {"name": "frozen berries", "quantity": 1, "unit": "cup"},
                    {
                        "name": "banana",
                        "quantity": 1,
                        "unit": "piece",
                        "notes": "frozen",
                    },
                    {"name": "almond milk", "quantity": 0.5, "unit": "cup"},
                    {"name": "granola", "quantity": 0.25, "unit": "cup"},
                    {"name": "chia seeds", "quantity": 1, "unit": "tbsp"},
                    {"name": "coconut flakes", "quantity": 2, "unit": "tbsp"},
                    {
                        "name": "fresh berries",
                        "quantity": 0.5,
                        "unit": "cup",
                        "notes": "for topping",
                    },
                ],
            },
            {
                "title": "Beef Stew",
                "description": "Hearty beef stew with potatoes and vegetables.",
                "servings": 6,
                "prep_time": 30,
                "cook_time": 120,
                "difficulty": "medium",
                "meal_type": "dinner",
                "dietary_restrictions": "none",
                "prep_instructions": "Cut beef into chunks. Chop vegetables.",
                "cook_instructions": "Brown beef. Add vegetables and broth. Simmer for 2 hours.",
                "ingredients": [
                    {
                        "name": "beef chuck",
                        "quantity": 2,
                        "unit": "lb",
                        "notes": "cut into chunks",
                    },
                    {
                        "name": "potatoes",
                        "quantity": 4,
                        "unit": "piece",
                        "notes": "cubed",
                    },
                    {
                        "name": "carrots",
                        "quantity": 4,
                        "unit": "piece",
                        "notes": "sliced",
                    },
                    {"name": "onion", "quantity": 1, "unit": "piece", "notes": "diced"},
                    {"name": "beef broth", "quantity": 4, "unit": "cup"},
                    {"name": "tomato paste", "quantity": 2, "unit": "tbsp"},
                    {"name": "thyme", "quantity": 1, "unit": "tsp", "notes": "dried"},
                    {"name": "bay leaves", "quantity": 2, "unit": "piece"},
                    {
                        "name": "flour",
                        "quantity": 2,
                        "unit": "tbsp",
                        "notes": "for thickening",
                    },
                ],
            },
            {
                "title": "Caprese Salad",
                "description": "Simple Italian salad with fresh mozzarella, tomatoes, and basil.",
                "servings": 4,
                "prep_time": 10,
                "cook_time": 0,
                "difficulty": "easy",
                "meal_type": "appetizer",
                "dietary_restrictions": "vegetarian",
                "prep_instructions": "Slice tomatoes and mozzarella. Wash basil leaves.",
                "cook_instructions": "No cooking required. Arrange ingredients and drizzle with dressing.",
                "ingredients": [
                    {
                        "name": "fresh mozzarella",
                        "quantity": 8,
                        "unit": "oz",
                        "notes": "sliced",
                    },
                    {
                        "name": "tomatoes",
                        "quantity": 2,
                        "unit": "piece",
                        "notes": "large, sliced",
                    },
                    {
                        "name": "fresh basil",
                        "quantity": 12,
                        "unit": "piece",
                        "notes": "leaves",
                    },
                    {"name": "extra virgin olive oil", "quantity": 2, "unit": "tbsp"},
                    {"name": "balsamic vinegar", "quantity": 1, "unit": "tbsp"},
                    {"name": "salt", "quantity": 0.25, "unit": "tsp"},
                    {"name": "black pepper", "quantity": 0.125, "unit": "tsp"},
                ],
            },
            {
                "title": "Fish Tacos",
                "description": "Light and flavorful fish tacos with lime crema.",
                "servings": 4,
                "prep_time": 25,
                "cook_time": 15,
                "difficulty": "medium",
                "meal_type": "lunch",
                "dietary_restrictions": "none",
                "prep_instructions": "Season fish. Prepare slaw and crema.",
                "cook_instructions": "Grill fish until flaky. Warm tortillas. Assemble tacos.",
                "ingredients": [
                    {
                        "name": "white fish fillets",
                        "quantity": 1,
                        "unit": "lb",
                        "notes": "mahi-mahi or tilapia",
                    },
                    {"name": "corn tortillas", "quantity": 8, "unit": "piece"},
                    {
                        "name": "cabbage",
                        "quantity": 2,
                        "unit": "cup",
                        "notes": "shredded",
                    },
                    {"name": "lime", "quantity": 2, "unit": "piece", "notes": "juiced"},
                    {"name": "sour cream", "quantity": 0.5, "unit": "cup"},
                    {
                        "name": "cilantro",
                        "quantity": 0.25,
                        "unit": "cup",
                        "notes": "chopped",
                    },
                    {"name": "cumin", "quantity": 1, "unit": "tsp"},
                    {"name": "chili powder", "quantity": 0.5, "unit": "tsp"},
                ],
            },
            {
                "title": "Oatmeal Cookies",
                "description": "Chewy oatmeal cookies with raisins and cinnamon.",
                "servings": 18,
                "prep_time": 15,
                "cook_time": 12,
                "difficulty": "easy",
                "meal_type": "dessert",
                "dietary_restrictions": "vegetarian",
                "prep_instructions": "Preheat oven to 350°F. Mix dry ingredients.",
                "cook_instructions": "Drop spoonfuls on baking sheet. Bake until edges are golden.",
                "ingredients": [
                    {"name": "old-fashioned oats", "quantity": 1.5, "unit": "cup"},
                    {"name": "all-purpose flour", "quantity": 1, "unit": "cup"},
                    {"name": "brown sugar", "quantity": 0.75, "unit": "cup"},
                    {
                        "name": "butter",
                        "quantity": 0.5,
                        "unit": "cup",
                        "notes": "softened",
                    },
                    {"name": "egg", "quantity": 1, "unit": "piece"},
                    {"name": "vanilla extract", "quantity": 1, "unit": "tsp"},
                    {"name": "cinnamon", "quantity": 0.5, "unit": "tsp"},
                    {"name": "baking soda", "quantity": 0.5, "unit": "tsp"},
                    {"name": "salt", "quantity": 0.25, "unit": "tsp"},
                    {"name": "raisins", "quantity": 0.5, "unit": "cup"},
                ],
            },
        ]

        self.stdout.write("Loading sample recipes...")

        for recipe_data in sample_recipes:
            # Extract ingredients data
            ingredients_data = recipe_data.pop("ingredients")

            # Create or get recipe
            recipe, created = Recipe.objects.get_or_create(
                title=recipe_data["title"],
                defaults={
                    **recipe_data,
                    "author": user,
                    "slug": slugify(recipe_data["title"]),
                },
            )

            if created:
                self.stdout.write(f"Created recipe: {recipe.title}")

                # Add ingredients
                for i, ingredient_data in enumerate(ingredients_data):
                    Ingredient.objects.create(
                        recipe=recipe, order=i + 1, **ingredient_data
                    )
                self.stdout.write(f"  Added {len(ingredients_data)} ingredients")
            else:
                self.stdout.write(f"Recipe already exists: {recipe.title}")

        self.stdout.write(
            self.style.SUCCESS(
                f"Successfully loaded {len(sample_recipes)} sample recipes!"
            )
        )
