# Generated by Django 4.2.23 on 2025-07-17 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "servings",
                    models.PositiveIntegerField(
                        default=4, help_text="Number of servings"
                    ),
                ),
                (
                    "prep_time",
                    models.PositiveIntegerField(
                        help_text="Preparation time in minutes"
                    ),
                ),
                ("prep_instructions", models.TextField()),
                (
                    "cook_time",
                    models.PositiveIntegerField(help_text="Cooking time in minutes"),
                ),
                ("cook_instructions", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                            ("dessert", "Dessert"),
                            ("appetizer", "Appetizer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.CharField(
                        choices=[
                            ("none", "No Restrictions"),
                            ("vegetarian", "Vegetarian"),
                            ("vegan", "Vegan"),
                            ("gluten_free", "Gluten Free"),
                            ("dairy_free", "Dairy Free"),
                            ("keto", "Keto"),
                            ("paleo", "Paleo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient_name", models.CharField(max_length=100)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("whole", "Whole"),
                            ("cup", "Cup"),
                            ("tablespoon", "Tablespoon"),
                            ("teaspoon", "Teaspoon"),
                            ("gram", "Gram"),
                            ("kilogram", "Kilogram"),
                            ("liter", "Liter"),
                            ("milliliter", "Milliliter"),
                            ("piece", "Piece"),
                            ("pinch", "Pinch"),
                            ("to taste", "To Taste"),
                            ("clove", "Clove"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the ingredient"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
